# Flashing the firmware

Uncomment and run the cell below to flash the hv507-switching-board firmware to an Arduino that is connected to the computer's serial port.

In [ ]:
#!python -m hv507_switching_board.bin.upload uno

In [1]:
import numpy as np
from hv507_switching_board import SerialProxy

In [2]:
try:
    # cleanup serial proxy object (if it exists)
    proxy.terminate()
except NameError:
    pass

# create a new serial proxy object
proxy = SerialProxy()
print proxy.properties
print 'ram_free =', proxy.ram_free()

base_node_software_version                                           0.12.post5
package_name                                              hv507-switching-board
display_name                                              hv507-switching-board
manufacturer                                                        Wheeler Lab
url                           http://github.com/wheeler-microfluidics/hv507-...
software_version                                                      0.1.post7
dtype: object
ram_free = 538


In [3]:
proxy.channel_count()

64

In [4]:
# this is the auto-generated accessor of the state_of_channels byte array
proxy._state_of_channels()

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [5]:
# set the state of all channels high using the auto-generated setter
proxy._set_state_of_channels([255] * (proxy.channel_count() / 8))
proxy._state_of_channels()

array([255, 255, 255, 255, 255, 255, 255, 255], dtype=uint8)

In [6]:
# access the state of channels through the new wrapped "property"
# (each byte in this array represents a single channel; 0 is low and 1 is high)
proxy.state_of_channels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [7]:
# set all channels to zero using the new wrapped "property"
proxy.state_of_channels = np.zeros(proxy.channel_count(), dtype=np.uint8)
proxy.state_of_channels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [8]:
# set all channels to one using the new wrapped "property"
proxy.state_of_channels = np.ones(proxy.channel_count(), dtype=np.uint8)
proxy.state_of_channels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)